In [75]:
import numpy as np

In [76]:
class CNN:
  def __init__(self, filter_size=3, n_filters=1, stride=1, padding=0, filter_passed_flag = False):
    self.n_filters = n_filters
    self.filter_size = filter_size
    self.filters = []
    self.stride = stride
    self.padding = padding
    self.filter_passed_flag = filter_passed_flag

  def forward(self,image, filter=0):
    # Defining Filters
    if(self.filter_passed_flag == False):
      for i in range(self.n_filters):
        self.filters.append(np.random.rand(image.shape[0], self.filter_size, self.filter_size))
    else:
      self.filters.append(filter)

    #Doing Convolution Operation
    conv_return = []
    for i in range(len(self.filters)):
      row_image = []
      currentFilter = self.filters[i]
      filter_pos = [0,0]
      while(True):
        if(filter_pos[0] + self.filter_size > image.shape[1]):
          break
        col_image = []
        while(True):
          if(filter_pos[1] + self.filter_size > image.shape[2]):
            break
          curr_image_part = image[:, filter_pos[0]:(filter_pos[0]+self.filter_size), filter_pos[1]:(filter_pos[1]+self.filter_size)]
          col_image.append(np.sum(np.multiply(currentFilter,curr_image_part)))
          filter_pos = [filter_pos[0], filter_pos[1]+self.stride]
        filter_pos = [filter_pos[0] + self.stride, 0]
        row_image.append(col_image)
      conv_return.append(row_image)
    
    return np.array(conv_return)

In [77]:
obj = CNN(filter_size=2, n_filters=7, stride=2, padding=0, filter_passed_flag = False)
image = np.random.rand(1,5,5)
return_image = obj.forward(image)
print(return_image.shape)

(7, 2, 2)


In [78]:
obj = CNN(filter_size=3, n_filters=1, stride=1, padding=0, filter_passed_flag = True)
inputImage = np.array([[[3,0,1,2,7,4],[1,5,8,9,3,1],[2,7,2,5,1,3],[0,1,3,1,7,8],[4,2,1,6,2,8],[2,4,5,2,3,9]],
                       [[3,0,1,2,7,4],[1,5,8,9,3,1],[2,7,2,5,1,3],[0,1,3,1,7,8],[4,2,1,6,2,8],[2,4,5,2,3,9]],
                       [[3,0,1,2,7,4],[1,5,8,9,3,1],[2,7,2,5,1,3],[0,1,3,1,7,8],[4,2,1,6,2,8],[2,4,5,2,3,9]]])
filter = np.array([[[1,0,-1],[1,0,-1],[1,0,-1]],
                   [[1,0,-1],[1,0,-1],[1,0,-1]],
                   [[1,0,-1],[1,0,-1],[1,0,-1]]])

print(inputImage.shape)
print(filter.shape)
return_image = obj.forward(inputImage, filter)
print(return_image)


(3, 6, 6)
(3, 3, 3)
[[[-15 -12   0  24]
  [-30  -6   6   9]
  [  0  -6 -12 -21]
  [ -9  -6  -9 -48]]]
